app = "destajo"
primary_region = "ams"

[build]

[env]
  DATABASE_URL = "sqlite:/data/destajo.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "datos_de_destajo"
  destination = "/data"
